// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.FluxoCaixa.PlanoContas.Data;

namespace Sample.Fluxo.Caixa.PlanoContas.Data.Migrations
{
    [DbContext(typeof(PlanoContasContext))]
    [Migration("20230131010630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.FluxoCaixa.PlanoContas.Domain.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ContaTipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bf47be9-926d-4beb-86d3-bda42a17382b"),
                            Ativo = true,
                            ContaTipo = 1,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 559, DateTimeKind.Local).AddTicks(5748),
                            Descricao = "Saldo Inicial"
                        },
                        new
                        {
                            Id = new Guid("9bc32333-7e08-4b47-8e20-e8ade041845f"),
                            Ativo = true,
                            ContaTipo = 2,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1827),
                            Descricao = "Vendas"
                        },
                        new
                        {
                            Id = new Guid("27ad1fc4-582f-40be-be67-ed3c8729b0ba"),
                            Ativo = true,
                            ContaTipo = 2,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1860),
                            Descricao = "Juros"
                        },
                        new
                        {
                            Id = new Guid("297f9108-0f10-4466-8819-228284385ecc"),
                            Ativo = true,
                            ContaTipo = 2,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1864),
                            Descricao = "Financiamento"
                        },
                        new
                        {
                            Id = new Guid("e043a7c3-96e5-4a3a-9533-ec2456fa8118"),
                            Ativo = true,
                            ContaTipo = 2,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1867),
                            Descricao = "Entrada"
                        },
                        new
                        {
                            Id = new Guid("ccc1011e-fe3e-4aba-b6a6-e9afb8646aec"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1869),
                            Descricao = "Fornecedores"
                        },
                        new
                        {
                            Id = new Guid("0cf8e5a2-0af0-4185-8494-d4b830c7d972"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1872),
                            Descricao = "Materiais"
                        },
                        new
                        {
                            Id = new Guid("09277791-7ffb-4f01-be9e-be7fa32c1273"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1874),
                            Descricao = "Retiradas sócios"
                        },
                        new
                        {
                            Id = new Guid("03c3a557-c972-49ad-b913-93304b6147ae"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1877),
                            Descricao = "Folha de pagamento"
                        },
                        new
                        {
                            Id = new Guid("230cb33d-b4cb-409d-a34b-fcbb672c8acc"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1884),
                            Descricao = "Aluguel"
                        },
                        new
                        {
                            Id = new Guid("2a867831-ee12-44f1-a689-17be2892d591"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1886),
                            Descricao = "Energia elétrica"
                        },
                        new
                        {
                            Id = new Guid("4e40c50d-a514-4fdd-9eb5-a551a4d41f55"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1889),
                            Descricao = "Telefone"
                        },
                        new
                        {
                            Id = new Guid("0b5c8e13-4bd0-4c3f-948e-7b64e58ea266"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1891),
                            Descricao = "Serviços contabilidade"
                        },
                        new
                        {
                            Id = new Guid("a8c400cc-dad9-4d8a-abc6-093777ad4f48"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1893),
                            Descricao = "Empréstimos"
                        },
                        new
                        {
                            Id = new Guid("39a87037-bfa0-4ff9-ad5a-7c04c2e13c2b"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1895),
                            Descricao = "Financiamentos"
                        },
                        new
                        {
                            Id = new Guid("69562cef-9241-4d24-8999-d333d91587aa"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1897),
                            Descricao = "Outros pagamentos"
                        },
                        new
                        {
                            Id = new Guid("3d4eadd8-dd32-428a-88cf-df3e8a89848f"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1899),
                            Descricao = "Investimentos"
                        },
                        new
                        {
                            Id = new Guid("59ac3e1a-0eed-4879-aaab-1f7f7c148d83"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1903),
                            Descricao = "Impostos"
                        },
                        new
                        {
                            Id = new Guid("27ab124e-207b-4ad2-8b3e-bcaa68c87120"),
                            Ativo = true,
                            ContaTipo = 3,
                            DataCadastro = new DateTime(2023, 1, 30, 22, 6, 29, 563, DateTimeKind.Local).AddTicks(1905),
                            Descricao = "Advogado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
